// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProduct struct {
	Name        string `json:"name"`
	Price       int    `json:"price"`
	ImageURL    string `json:"imageUrl"`
	Description string `json:"description"`
	ShopID      string `json:"shopId"`
}

type NewShop struct {
	Name    string `json:"name"`
	UserID  string `json:"userId"`
	LogoURL string `json:"logoUrl"`
}

type Product struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Price       int    `json:"price"`
	ImageURL    string `json:"imageUrl"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
	Shop        *Shop  `json:"shop,omitempty"`
}

type ProductFilter struct {
	Name  *string `json:"name,omitempty"`
	Slug  *string `json:"slug,omitempty"`
	Limit int     `json:"limit"`
}

type Shop struct {
	ID         string   `json:"id"`
	UserID     string   `json:"userId"`
	Name       string   `json:"name"`
	LogoURL    string   `json:"logoUrl"`
	IsVerified bool     `json:"isVerified"`
	ProductID  []string `json:"productId,omitempty"`
	Status     string   `json:"status"`
	CreatedAt  string   `json:"createdAt"`
	UpdatedAt  string   `json:"updatedAt"`
}

type ShopFilter struct {
	Name   *string `json:"name,omitempty"`
	UserID *string `json:"userId,omitempty"`
	Limit  int     `json:"limit"`
}

type UpdateProduct struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Price    *int    `json:"price,omitempty"`
	ImageURL *string `json:"imageUrl,omitempty"`
}
