// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProduct struct {
	Name     string `json:"name"`
	Price    int    `json:"price"`
	ImageURL string `json:"imageUrl"`
}

type Product struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Price     int    `json:"price"`
	ImageURL  string `json:"imageUrl"`
	Slug      string `json:"slug"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type ProductFilter struct {
	Name  *string `json:"name,omitempty"`
	Slug  *string `json:"slug,omitempty"`
	Limit int     `json:"limit"`
}

type UpdateProduct struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Price    *int    `json:"price,omitempty"`
	ImageURL *string `json:"imageUrl,omitempty"`
}
